name: Test ClassPass Booking

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome & ChromeDriver (Fixed)
        run: |
          sudo apt update
          sudo apt install -y wget curl unzip xvfb chromium-browser

          # Manually specify the latest working ChromeDriver version
          CHROMEDRIVER_VERSION="122.0.6261.111"
          echo "Using fixed ChromeDriver version: $CHROMEDRIVER_VERSION"

          # Download & Install ChromeDriver
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          echo "✅ Chrome & ChromeDriver installed successfully!"

      - name: Run ClassPass Booking Test
        run: python test_booking.py  # Ensure this script correctly performs Selenium actions
